apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fleet-networking-controller
  namespace: fleet-member-member-1
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - update
  - watch
  - patch
- apiGroups: 
  - networking.fleet.azure.com
  - cluster.kubernetes-fleet.io
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fleet-networking-controller
  namespace: fleet-member-member-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fleet-networking-controller
subjects:
  - kind: User
    name: 96ed43af-4a7f-49ae-92bf-9201b5e4fce9
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fleet-networking-controller
  namespace: fleet-member-member-2
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - update
  - watch
  - patch
- apiGroups: 
  - networking.fleet.azure.com
  - cluster.kubernetes-fleet.io
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fleet-networking-controller
  namespace: fleet-member-member-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fleet-networking-controller
subjects:
  - kind: User
    name: 9953fcdd-da5c-41b9-ac5c-abd41f4bf16e
